# Copyright 2016 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Put all your resources under `resources:`. For each resource, you need:
# - The type of resource. In this example, the type is a Compute VM instance.
# - An internal name for the resource.
# - The properties for the resource. In this example, for VM instances, you add
#   the machine type, a boot disk, network information, and so on.
#
# For a list of supported resources,
# see https://cloud.google.com/deployment-manager/docs/configuration/supported-resource-types.

imports:
- path: ./templates/compute-engine-template.jinja
  name: compute-engine-template.jinja
- path: ./templates/splunk-node.jinja
  name: splunk-node.jinja
- path: ./templates/splunk-peer.jinja
  name: splunk-peer.jinja
- path: ./network/network-template.jinja
  name: network-template.jinja
- path: ./network/firewall-template.jinja
  name: firewall-template.jinja
- path: ./initial-scripts/peer.sh
  name: peer.sh
- path: ./initial-scripts/node.sh
  name: node.sh

resources:
- name: compute-engine-setup
  type: compute-engine-template.jinja
